instance creation
style: aStyle weight: aWeight stretch: aStretch size: aSize sizeAdjust: aSizeAdjust language: aLanguage isExplicitLanguage: aExplicitLanguage languageOverride: aLanguageOverride isSystemFont: aSystemFont isPrinterFont: aPrinterFont isWeightSynthesis: aWeightSynthesis isStyleSynthesis: aStyleSynthesis

	^ self
		primCreateStyle: aStyle
		weight: aWeight
		stretch: aStretch
		size: aSize
		sizeAdjust: aSizeAdjust
		language: aLanguage
		isExplicitLanguage: aExplicitLanguage
		languageOverride: aLanguageOverride
		isSystemFont: aSystemFont
		isPrinterFont: aPrinterFont
		isWeightSynthesis: aWeightSynthesis
		isStyleSynthesis: aStyleSynthesis