Class {
	#name : #SpartaCairoSingleSourceFilter,
	#superclass : #SpartaCairoFilter,
	#traits : 'TSpartaFilterSource',
	#classTraits : 'TSpartaFilterSource classTrait',
	#category : 'Sparta-Cairo-Filters'
}

{ #category : #dispatch }
SpartaCairoSingleSourceFilter >> sourceCanvas: aSpartaCanvas [
]

{ #category : #dispatch }
SpartaCairoSingleSourceFilter >> sourceFilter: aFilter [

]

{ #category : #dispatch }
SpartaCairoSingleSourceFilter >> sourceSurface: aSurface [

]
