SystemOrganization addCategory: #'Sparta-Moz2D'!
SystemOrganization addCategory: 'Sparta-Moz2D-Builders'!
SystemOrganization addCategory: 'Sparta-Moz2D-Enums'!
SystemOrganization addCategory: 'Sparta-Moz2D-Examples'!
SystemOrganization addCategory: 'Sparta-Moz2D-External'!
SystemOrganization addCategory: 'Sparta-Moz2D-Filters'!
SystemOrganization addCategory: 'Sparta-Moz2D-Filters Enum'!
SystemOrganization addCategory: 'Sparta-Moz2D-GFX'!
SystemOrganization addCategory: 'Sparta-Moz2D-Library'!
SystemOrganization addCategory: 'Sparta-Moz2D-Paints'!
SystemOrganization addCategory: 'Sparta-Moz2D-Path'!
SystemOrganization addCategory: 'Sparta-Moz2D-Preferences'!
SystemOrganization addCategory: 'Sparta-Moz2D-Skia'!
SystemOrganization addCategory: 'Sparta-Moz2D-Text'!
SystemOrganization addCategory: 'Sparta-Moz2D-Text-Callbacks'!
SystemOrganization addCategory: 'Sparta-Moz2D-Text-Enums'!
SystemOrganization addCategory: 'Sparta-Moz2D-Text-Metrics'!
