SystemOrganization addCategory: #'Sparta-Core'!
SystemOrganization addCategory: 'Sparta-Core-Builders'!
SystemOrganization addCategory: 'Sparta-Core-Filters'!
SystemOrganization addCategory: 'Sparta-Core-Math'!
SystemOrganization addCategory: 'Sparta-Core-Paints'!
SystemOrganization addCategory: 'Sparta-Core-Path'!
SystemOrganization addCategory: 'Sparta-Core-Text'!
SystemOrganization addCategory: 'Sparta-Core-Utils'!
