*Sparta-Moz2D
mozInitializeFrom: aMozFontMetrics
	"Initialize me from external structure"
	
	aveCharWidth := aMozFontMetrics aveCharWidth.
	capHeight := aMozFontMetrics capHeight.
	emAscent := aMozFontMetrics emAscent.
	emDescent := aMozFontMetrics emDescent.
	emHeight := aMozFontMetrics emHeight.
	externalLeading := aMozFontMetrics externalLeading.
	internalLeading := aMozFontMetrics internalLeading.
	maxAdvance := aMozFontMetrics maxAdvance.
	maxAscent := aMozFontMetrics maxAscent.
	maxDescent := aMozFontMetrics maxDescent.
	maxHeight := aMozFontMetrics maxHeight.
	spaceWidth := aMozFontMetrics spaceWidth.
	strikeoutOffset := aMozFontMetrics strikeoutOffset.
	strikeoutSize := aMozFontMetrics strikeoutSize.
	underlineOffset := aMozFontMetrics underlineOffset.
	underlineSize := aMozFontMetrics underlineSize.
	xHeight := aMozFontMetrics xHeight.
	zeroOrAveCharWidth := aMozFontMetrics zeroOrAveCharWidth