Class {
	#name : #SpartaUnimplementedFontFaceBuilder,
	#superclass : #SpartaFontFaceBuilder,
	#category : #'Sparta-Core-Builders - Unimplemented'
}

{ #category : #building }
SpartaUnimplementedFontFaceBuilder >> build [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchCondensed [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchExpanded [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchExtraCondensed [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchExtraExpanded [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchNormal [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchReset [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchSemiCondensed [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchSemiExpanded [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchUltraCondensed [
]

{ #category : #stretch }
SpartaUnimplementedFontFaceBuilder >> stretchUltraExpanded [
]

{ #category : #style }
SpartaUnimplementedFontFaceBuilder >> styleItalic [
]

{ #category : #style }
SpartaUnimplementedFontFaceBuilder >> styleNormal [
]

{ #category : #style }
SpartaUnimplementedFontFaceBuilder >> styleOblique [
]

{ #category : #style }
SpartaUnimplementedFontFaceBuilder >> styleReset [
]
