Class {
	#name : #SpartaUnimplementedSurfacePaint,
	#superclass : #SpartaUnimplementedPaint,
	#traits : 'TSpartaSurfacePaint',
	#classTraits : 'TSpartaSurfacePaint classTrait',
	#category : #'Sparta-Core-Builders - Unimplemented'
}

{ #category : #'sampling filters' }
SpartaUnimplementedSurfacePaint >> samplingArea: aRectangle [
]

{ #category : #'sampling filters' }
SpartaUnimplementedSurfacePaint >> samplingGood [
]

{ #category : #'sampling filters' }
SpartaUnimplementedSurfacePaint >> samplingLinear [
]

{ #category : #'sampling filters' }
SpartaUnimplementedSurfacePaint >> samplingPoint [
]

{ #category : #'sampling filters' }
SpartaUnimplementedSurfacePaint >> samplingSentinel [
]

{ #category : #accessing }
SpartaUnimplementedSurfacePaint >> source: aSurface [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaFillCircle: aSpartaCircle with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaFillPath: aPath with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaFillRectangle: aRectangle with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaFillRoundedRectangle: aRectangle with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaStrokeCircle: aSpartaCircle with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaStrokeLine: aLine with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaStrokePath: aPath with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaStrokeRectangle: aPath with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedSurfacePaint >> spartaStrokeRoundedRectangle: aRoundedRectangle with: aStrokePainter [
]
