Class {
	#name : #SpartaUnimplementedPaint,
	#superclass : #Object,
	#traits : 'TSpartaPaint',
	#classTraits : 'TSpartaPaint classTrait',
	#category : #'Sparta-Core-Builders - Unimplemented'
}

{ #category : #'extend modes' }
SpartaUnimplementedPaint >> clamp [
]

{ #category : #'extend modes' }
SpartaUnimplementedPaint >> reflect [
]

{ #category : #'extend modes' }
SpartaUnimplementedPaint >> repeat [
]

{ #category : #'extend modes' }
SpartaUnimplementedPaint >> repeatX [
]

{ #category : #'extend modes' }
SpartaUnimplementedPaint >> repeatY [
]

{ #category : #accessing }
SpartaUnimplementedPaint >> transformation: aMatrix [
]
