Class {
	#name : #SpartaUnimplementedRadialGradientPaint,
	#superclass : #SpartaUnimplementedGradientPaint,
	#traits : 'TSpartaRadialGradientPaint',
	#classTraits : 'TSpartaRadialGradientPaint classTrait',
	#category : #'Sparta-Core-Builders - Unimplemented'
}

{ #category : #accessing }
SpartaUnimplementedRadialGradientPaint >> center: aPoint [
]

{ #category : #accessing }
SpartaUnimplementedRadialGradientPaint >> radius: aNumber [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaFillCircle: aSpartaCircle with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaFillPath: aPath with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaFillRectangle: aRectangle with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaFillRoundedRectangle: aRectangle with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaStrokeCircle: aSpartaCircle with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaStrokeLine: aLine with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaStrokePath: aPath with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaStrokeRectangle: aPath with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedRadialGradientPaint >> spartaStrokeRoundedRectangle: aRoundedRectangle with: aStrokePainter [
]
