Class {
	#name : #SpartaUnimplementedLinearGradientPaint,
	#superclass : #SpartaUnimplementedGradientPaint,
	#traits : 'TSpartaLinearGradientPaint',
	#classTraits : 'TSpartaLinearGradientPaint classTrait',
	#category : #'Sparta-Core-Builders - Unimplemented'
}

{ #category : #accessing }
SpartaUnimplementedLinearGradientPaint >> begin: aPoint [
]

{ #category : #accessing }
SpartaUnimplementedLinearGradientPaint >> end: aPoint [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaFillCircle: aSpartaCircle with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaFillPath: aPath with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaFillRectangle: aPath with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaFillRoundedRectangle: aRoundedRectangle with: aFillPainter [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaStrokeCircle: aSpartaCircle with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaStrokeLine: aLine with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaStrokePath: aPath with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaStrokeRectangle: aRectangle with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedLinearGradientPaint >> spartaStrokeRoundedRectangle: aRoundedRectangle with: aStrokePainter [
]
