Class {
	#name : #SpartaUnimplementedBoxShadowPaint,
	#superclass : #SpartaUnimplementedPaint,
	#traits : 'TSpartaBoxShadowPaint',
	#classTraits : 'TSpartaBoxShadowPaint classTrait',
	#category : #'Sparta-Core-Builders - Unimplemented'
}

{ #category : #accessing }
SpartaUnimplementedBoxShadowPaint >> color: aNumber [
]

{ #category : #accessing }
SpartaUnimplementedBoxShadowPaint >> offset: aPoint [
]

{ #category : #accessing }
SpartaUnimplementedBoxShadowPaint >> radius: aNumber [
]

{ #category : #dispatch }
SpartaUnimplementedBoxShadowPaint >> spartaStrokeCircle: aSpartaCircle with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedBoxShadowPaint >> spartaStrokeLine: aLine with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedBoxShadowPaint >> spartaStrokePath: aPath with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedBoxShadowPaint >> spartaStrokeRectangle: aPath with: aStrokePainter [
]

{ #category : #dispatch }
SpartaUnimplementedBoxShadowPaint >> spartaStrokeRoundedRectangle: aRoundedRectangle with: aStrokePainter [
]
