"
I am a specific gamma transfer filter.

https://docs.webplatform.org/wiki/svg/elements/feComponentTransfer
https://www.w3.org/TR/filter-effects/#feComponentTransferElement
"
Trait {
	#name : #TSpartaGammaTransferFilter,
	#category : #'Sparta-Core-Filters'
}

{ #category : #accessing }
TSpartaGammaTransferFilter >> amplitudeAlpha: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> amplitudeBlue: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> amplitudeGreen: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> amplitudeRed: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> exponentAlpha: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> exponentBlue: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> exponentGreen: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> exponentRed: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> offsetAlpha: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> offsetBlue: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> offsetGreen: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaGammaTransferFilter >> offsetRed: aFloat [
	^ self explicitRequirement
]
