Trait {
	#name : #TSpartaSpotLight,
	#category : 'Sparta-Core-Filters'
}

{ #category : #accessing }
TSpartaSpotLight >> limitingConeAngle: aFloat [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaSpotLight >> pointsAtX: x y: y z: z [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaSpotLight >> positionX: x y: y z: z [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaSpotLight >> specularExponent: aFloat [
	^ self explicitRequirement
]
