Trait {
	#name : #TSpartaTransferFilter,
	#category : #'Sparta-Core-Filters'
}

{ #category : #accessing }
TSpartaTransferFilter >> disableAlpha: aBoolean [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaTransferFilter >> disableBlue: aBoolean [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaTransferFilter >> disableGreen: aBoolean [
	^ self explicitRequirement
]

{ #category : #accessing }
TSpartaTransferFilter >> disableRed: aBoolean [
	^ self explicitRequirement
]
