advanced options
enableFontMetrics

	fontMetrics := MozFontMetrics externalNew.
	fontMetrics autoRelease.
	fontMetrics
		aveCharWidth: 0;
		emAscent: 0;
		emDescent: 0;
		emHeight: 0;
		externalLeading: 0;
		internalLeading: 0;
		maxAdvance: 0;
		maxAscent: 0;
		maxDescent: 0;
		maxHeight: 0;
		spaceWidth: 0;
		strikeoutOffset: 0;
		strikeoutSize: 0;
		underlineOffset: 0;
		underlineSize: 0;
		xHeight: 0;
		zeroOrAveCharWidth: 0